Feature: Gas Costs For Transaction Deployment

  Check deployment costs as generated by ContractDeploymentGasCostTestPackProducer in the compat/runner project

  Background: Account has plenty funds
    Given account 0x5E4DE7 has nonce 0
    Given account 0x5E4DE7 has balance 1000000000000000000

  Scenario Outline: Amount of gas used and sender balance is correct when deploying the NumberFunctions contract - <hardFork>
    Given a transaction with contents:
      | from     | to | value | gasPrice | gasLimit | nonce |
      | 0x5E4DE7 |    | 0     | 400      | 3000000  | 0     |
    And transaction has data from classpath file "org/kevem/compat/NumberFunctions.bin"
    And <hardFork> hard fork features are enabled
    When the transaction is executed
    Then transaction used <gasUsed> gas
    And account 0x5E4DE7 now has balance <balanceRemaining>

    Examples:
      | hardFork  | gasUsed | balanceRemaining   |
      | Byzantium | 722561  | 999999999710975600 |
      | Istanbul  | 594121  | 999999999762351600 |

